leftnav:
- identifier: ba49cd5d-604e-6c49-fdcf-69d926c958cf
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 6a15263e-faee-2c43-f50e-d6647edd77c3
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: d34bfeff-7138-9d50-93cb-1f7899d34696
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 389bc200-2b0d-49cb-03b7-85d6706f8d77
  name: Assignments
  url: /pages/assignments/
  weight: 40
- identifier: 133a6915-0008-e564-0179-7e4d2516b03f
  name: First Writing Assignment
  parent: 389bc200-2b0d-49cb-03b7-85d6706f8d77
  url: /pages/assignments/first-writing-assignment
  weight: 50
- identifier: 25f10b48-02da-aa8a-9ca1-211b1b746171
  name: Second Writing Assignment
  parent: 389bc200-2b0d-49cb-03b7-85d6706f8d77
  url: /pages/assignments/second-writing-assignment
  weight: 60
- identifier: 53296a7c-ec64-118c-2dfc-31e306cecdc7
  name: Final Writing Assignment
  parent: 389bc200-2b0d-49cb-03b7-85d6706f8d77
  url: /pages/assignments/final-writing-assignment
  weight: 70
